@url_dev=http://localhost:9000/api/v1
@access_token=eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2OTI1YzY5OTZlMTkwM2Y1NjIxYTk5MjEiLCJpYXQiOjE3NjQwODQyMjAsImV4cCI6MTc2NDI1NzAyMH0.sysWgIE8fLwstMWrfoL1U4qz459r13xYfUaAZGykzI2x8AxJsmlmFwpsgPDGIzYK8euIgkWs_k9iLLfgBHf9xF5zj3ZwJsFPwUqROfGio_eHIEDmgxMm3aoVke8sDI4MImYpmp056I8nwIOS6oiDCD0szR0YThbqRvksoM8b1EJyL7ZeeSbHHQFcOlSjubnKG3MSTtnY0USzU6eKGZVBZy2oM8Vh4Ibd61haHFOppFFiM2RETlhlbYHp8g-PhcbzcP8IUju9IXbSGWp_g8CEtZ9XkkEhLVNvMvEtiYbqKYWSJ14rONzKJOheIxyb3KH8DFnMjCZEc4AzoM7tV35TJhXToAv6YUZY06WwXJmeUsNPFbDICTWWSxlX6jGhHq4joBr-VhVrOjGYmJ3-BdW-Ce0XI7bV2cnjhL9NmxTC4gDgyEtMQ-Wps_KhiDqKKzlsPpPXu9KLa5TaVH0rjx7QFQB3vp0IKL49XxePBjE0tBQECNtIY_su2PzkTrKJdvnptPEZK_Ususc25cUOaHF7Z3QtxgUVoR8EsjjgsLp_ACy773Leny2Ra03oDvW4oav7qbVySPuFMdlTn7sO1mTlB42ASqex1E7WqdeCvh59PkjwnbetCRx2egBGnWVs8LsOAmPtV4qD4GO8gUWen01QW0DMI6eh69CWUwKCegPlc0Q
@refresh_token=eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2OTI1YzY5OTZlMTkwM2Y1NjIxYTk5MjEiLCJpYXQiOjE3NjQwODQyMjAsImV4cCI6MTc2NDY4OTAyMH0.vsIqP64r_SfKUJNn5NECKhCuvh5THOwzv0GfRaAJuj7S80BuF7DdY4__bIizKOmMXISuuE8h6e6kEeVYJ6b5FmuaIxYF-DkBvcxeqfVcoLV7Ke-w5WEuZHa6IVRhcl6zmDa8je6REhQbWO9fTdfXw-aOSxmE-A4u5KJqRyEBv51UIBZLiXQ0gH7kqlWf45LnOrADr96nVBRpR-GOemGthX5jEGjARpP3u1CS5yqVNxdjB6ATMU86tTJJHD9LG3kswd6y8fTG1SsK08SaxegoIGsd3Uugwly9SZzsMoGtjFzkQBw_zWRPkrJ6foliLCf7dRRk-AZreV62_VjutMBoEW8jrwm_nn7uTpJ8H7ttUXhExrg61gp-fIIxKvVcaptKEeLN1lD6xkDbVFNmEsJl-YEY9r-KVws5aFbkCpK0NflmCN0BXMIBJSLb9DBINhJjJYNjjhJmTPk3ep0zH6irZxBpp6p82WNCN6jPWIEbxJExet4SR3Q57AcWwDNNveSHmidGGukLjq34GihNP_pYWrbo8v4BYkMm2lBUWr6YNTZ55m1e_LnGjL7IbUHCn2Xb46kop87HdArfc3oS1a9g0iiYb97yNyTOLhpJP2rhkTfLBAXcFVnG8DYjD4ZviH530fIFMSZMK-72omxstJ75QtOps-JmVxdVoVJ6fHSZEkM

### Create a api key for testing
POST {{url_dev}}/api-keys

### signup
POST {{url_dev}}/shop/signup
Content-Type: application/json
x-api-key: d1f72141cda389d4266d8a5604aa2c9a5bef71ea53498cf706bbd81248587d28

{
    "email": "buithanhliem@gmail.com",
    "password": "liemdev@123"
}

### login
POST {{url_dev}}/shop/login
Content-Type: application/json
x-api-key: d1f72141cda389d4266d8a5604aa2c9a5bef71ea53498cf706bbd81248587d28

{
    "email": "buithanhliem@gmail.com",
    "password": "liemdev@123"
}

### refresh token
POST {{url_dev}}/shop/refresh-token
Content-Type: application/json
x-api-key: d1f72141cda389d4266d8a5604aa2c9a5bef71ea53498cf706bbd81248587d28
x-client-key: 6925c6996e1903f5621a9921
Authorization: Bearer {{access_token}}

{
    "refreshToken": "{{refresh_token}}"
}


### logout
POST {{url_dev}}/shop/logout
Content-Type: application/json
x-api-key: d1f72141cda389d4266d8a5604aa2c9a5bef71ea53498cf706bbd81248587d28
x-client-key: 6925c6996e1903f5621a9921
Authorization: Bearer {{access_token}}
