@url_dev=http://localhost:9000/api/v1

### Create a cart
POST {{url_dev}}/cart/
Content-Type: application/json
x-api-key: 018f3027501094af9877f52528384d50c0dfd2bbc06a8ed02000a9d41a893924

{
    "userId": "692a64cf3ecec2962c7aba10",
    "product": {
        "_id": "692aab34a52c29f5545e8e25",
        "quantity": 10
    }
}

### Update a cart
POST {{url_dev}}/cart/update
Content-Type: application/json
x-api-key: 018f3027501094af9877f52528384d50c0dfd2bbc06a8ed02000a9d41a893924

{
    "userId": "692a64cf3ecec2962c7aba10",
    "shopOrderIds": [
        {
            "shopId": "692a64183ecec2962c7aba09",
            "itemProducts": [
                {
                    "quantity": 0, 
                    "oldQuantity": 1 ,
                    "shopId": "692a64183ecec2962c7aba09",
                    "productId": "692a65013ecec2962c7aba26"
                }
            ],
            "version": 100
        }
    ]
}

### Delete product item
DELETE  {{url_dev}}/cart/
Content-Type: application/json
x-api-key: 018f3027501094af9877f52528384d50c0dfd2bbc06a8ed02000a9d41a893924

{
    "userId": "692a64cf3ecec2962c7aba10",
    "productId": "692a65013ecec2962c7aba26"
}

### Get a cart
GET {{url_dev}}/cart?userId=692a64cf3ecec2962c7aba10
Content-Type: application/json
x-api-key: 018f3027501094af9877f52528384d50c0dfd2bbc06a8ed02000a9d41a893924