@url_dev=http://localhost:9000/api/v1
@access_token=eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2OTJiZWJjNGFkZmVlNzljMDkwNTBkMmEiLCJpYXQiOjE3NjQ0ODYxMjQsImV4cCI6MTc2NDY1ODkyNH0.jBe7STRBaHuh5Wjq7VmjiDXlfp1keReRmWKER2uCzNKAaO1qNAjZamU2JQuNZh1uxBSy1QWaotIHMaTlH-gFrJ0Vgd68M9XtL99ZlPYsCTPtCAAIRUFTemHkkFHc5aSnat5oxEBR9PbLwm--i-Q5zCDDc1Zf2R3h-TePEWqwLr0-2yq4oWIlNBrtMTm366ol09iEzpqtio_PjFxXcVOhPSKkwm-omJxw_fvtPvhThVN7xuM_JkuobXYlpAs0akevJwYvDE4ov1URT7KzBdiY9UaOge1HQz3AhNaj39ge5x0V7tBbvNhSE3tElScYqdxnPu1y5Q4VZDFcCrMq6ce7LMUPygm0HYnZiELpabAeQh_iiTf-b6K251KkL4Kn_Kl8Ke7bo0r8uKTLfbM_FFfHi766imlCUe5nvp8eubiuoLAsIR-V0nN7lHiq9J14Mdl4515lopZFMK2HTU2V9KnA0ByOMvLIRyi8coS27ZkdBgu295NR4egZPWK_7CUwE8mt22MtLBMY5R-OJUjDu8cZMGP3dsjbHPAoGpFcXKz79tSxu-ZVxK9-ONS8EBkP8vBBUmoJrjoGw3oivFqjRDjIZyhpdf3s3aejxXUp-bd32tA4ZlpS83ewFfe7PLvIMHmZF5OOsDWcdLJwtJWbSrV4IYSwElMI4ZoP_DuQPJplsXo
@refresh_token=eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2OTJiZWJjNGFkZmVlNzljMDkwNTBkMmEiLCJpYXQiOjE3NjQ0ODYxMjQsImV4cCI6MTc2NTA5MDkyNH0.Zqis7F8AQoFLDFY9b-PBxHSEQY03k-GegJXsk7Q37r4WNQ-f4S4QXR9dgdi1GCyP4igOW9GOZasFz-3WFS2E15uh3sMuYWK7xqh_X8z7VRG548KyO4OCZfcD1RK_Lf7i04i6I1ViPu9i2thZKgxuDOjCtgWhEbshxFJW6YWBKgfeXKZRNpsRFu_3lv7HNG3C8_OnlzpDjHGH94ygDvq7PdWVx2bju9inYQ6ryi75uSER4ZlDZqwdmIY0yqG9xzasFiQ3Jllb4Qjx6SUp2SbZa0rdnwTa3M13_5o5MjM3sMBOEclw-Uc9HFh3iF0SP7MFUAleTpQ9NvC1qCJVsdoy9BYjBgLlheyCXbz2aaRYL0t2BBTsjfuZ0we_YM7qIbrDwwfjVNOu2IH52j0PpGrkC9MQ_EkshM9zUGXuCatixrx-NIpjV25mpiekh8R5vX-VH_IHPFvCeK_WBrag-mEJF0-jKBtfxP7ewfpN6e16zaH94HAWEvsZm13bvSyHqctPYEyhpv3ldQtnIH1rxASKFZS8B5RjypTvBkaRYuT2bHB8DUpaABvLmNR-LmIG1PNE7XfRQUkorEaSa3lF2-cXoZy0GOF8aeRSiUDakfzkueE4oQ_DAsoWm9SbPFVESeVcsvyaqA5HxjRtvmhU4-INA7ApAv369n_YeBA3hHOB74w

### Checkout review
POST {{url_dev}}/checkout/review
Content-Type: application/json
x-api-key: 7baee00ea02c5b34d0b84a9f5f64cf3bc62c73f49048c37abfff55366f96375e
x-client-key: 692a64183ecec2962c7aba09
Authorization: Bearer {{access_token}}

{
    "cartId": "692a7b5a6f112a4546bd1674",
    "userId": "692a64cf3ecec2962c7aba10",
    "shopOrderIds": [
        {
            "shopId": "692a64183ecec2962c7aba09", 
            "shopDiscounts": [
                {
                    "code": "SHOP_000"
                }
            ],
            "itemProducts": [
                {
                    "_id": "692a65013ecec2962c7aba26",
                    "shopId": "692a64183ecec2962c7aba09",
                    "quantity": 6
                }
            ]
        },
        {
            "shopId": "692aaacea52c29f5545e8e1b", 
            "shopDiscounts": [],
            "itemProducts": [
                {
                    "_id": "692aab34a52c29f5545e8e25",
                    "shopId": "692aaacea52c29f5545e8e1b",
                    "quantity": 10
                }
            ]
        }
    ]
}

### checkout order
POST {{url_dev}}/checkout/order
Content-Type: application/json
x-api-key: 7baee00ea02c5b34d0b84a9f5f64cf3bc62c73f49048c37abfff55366f96375e
x-client-key: 692a64183ecec2962c7aba09
Authorization: Bearer {{access_token}}

{
    "cartId": "692a7b5a6f112a4546bd1674",
    "userId": "692a64cf3ecec2962c7aba10",
    "shopOrderIds": [
        {
            "shopId": "692a64183ecec2962c7aba09", 
            "shopDiscounts": [
                {
                    "code": "SHOP_000"
                }
            ],
            "itemProducts": [
                {
                    "_id": "692a65013ecec2962c7aba26",
                    "shopId": "692a64183ecec2962c7aba09",
                    "quantity": 6
                }
            ]
        },
        {
            "shopId": "692aaacea52c29f5545e8e1b", 
            "shopDiscounts": [],
            "itemProducts": [
                {
                    "_id": "692aab34a52c29f5545e8e25",
                    "shopId": "692aaacea52c29f5545e8e1b",
                    "quantity": 10
                }
            ]
        }
    ]
}