@url_dev=http://localhost:9000/api/v1
@access_token=eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2OTI4NTZhOTFjYWJiODE5NGFmMjE3NmUiLCJpYXQiOjE3NjQyNTEzMzcsImV4cCI6MTc2NDQyNDEzN30.H8as-TLMgIYYhPFvmeQHTNuBXAe7XH5wgzCyy7X9GfnYgyYPccmqh2DyKajCc30vWwrXvTszELhCIq_JCuHRcb1fTqhMF951y6L9mN-ggmK_NMnRIYzUA7xYe2j2uZUfBMJn0GgqCAa35SToNwHQVgDmgJhlDS4FmDO0sVpqvOoHjh1KycMh9dEMnv7MQccl9wo4vjvDTZcokUQYaF4JoTbDIwtBlcYE_yZ7gv3kW8TDMBhMLoIXCW9l3kxBWJyNUFDS5772KB_h4jcT0cTqe37hQ8DMVARVmLwEKQT1RRFLzSPLQiIM4xEcs-lCyeBOdQWb9rcoUFEfNAaxz9eudqyQw8zWbydJB5SFtHfIBFOX_yrhNnLXPd_n7zNrdmBUY2SvaWj9rOpRwGdtab36vHOZ0GZWV9OuCwYpXmqW7HLR7N4kyYwHF2C372to15scvdYbUe6cB1Dw1GQd_OSoUYIG8aDZX2cFHO1BTjkF_FXiSbLiNLcktNmIfWNPz7OIyk3XkF82bAwktVzu8lU7HU0UhnlCSBbPcZAkyIT3dS7pjw6-GzuIDzcLwoZQV6ulhP-WN5zzNe50XQXRD5LewqJFOhEZFUmVUtoEKZ7sKVEbSIkL7YII3wOukOK6E0i77qoaZ2XSaJtHDY_tJUn_iPu3WK7FCxmYocJ881p3VqQ
@refresh_token=eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2OTI4NTZhOTFjYWJiODE5NGFmMjE3NmUiLCJpYXQiOjE3NjQyNTEzMzcsImV4cCI6MTc2NDg1NjEzN30.OuRJxw3QhexET2ski1YloE98JtWk8DKU67q9aiK5w7rsfeYhlG1T-5w2z6SVvKOxUp_YH_eBcBXVD42vbDpk6qpgYaw_ZL_JGhaP7De1eCJEVnSdloH6Fw9ZJkzUA3nD22l8Ag6DL9_D-D_leScTfFoe2qJYaCgY-VrDYqR02v4H3uwrmCAQTb23KufCGl1QDHwPg-t_g5bqSsgFxmLw7KFwDdntHyOInELdTJbrPZc400_ywOJIX9fpZSCUBcXr-oYJvkxFG3yzr9JiYRxNmfL9aZhqya73jlbMOV-z-kiMn2cLPdLTvAs6hUA-EAYwix2FuKDRCBpS3IZJJYn6vIrxkvbvhn5pQiZeFEzyfc4G34nUaNS0XTzmhxEErPRCgB5bPgQP6AUtWeqHGK850gh9j7FV1cj5ra-V_p3cBuRqNbSnbQbu2zuagH9E7pGjlSls4TgWqj3KgUzy6inRSdeT-gORwso9KNrTUCT-HpVUJdWbs7QXv-JY0xFUWAhZwUn5WnrbD9XW9QgZBUWyGcE9kHxud3YVvGrK1Xm76lTdzEbkZTkuULMKNz373BgOSIRfdy1vShmuz56fEFstaX7J474t2xuhpudeHl-GhpqIZ_RC6nyRvG_EM_sg0Bd8xGGV4EjUw1qketdCXQoEXQalcyo03g5QS2T9FyoNIJ4

### cerate product
POST {{url_dev}}/product/
Content-Type: application/json
x-api-key: c3c035e9650d2782af88d2139eb62e08ba4a4c8e5c083a5e2ee7e9ffae9e8515
x-client-key: 692856a91cabb8194af2176e
Authorization: Bearer {{access_token}}

{
    "name": "Ghế quỳ hiện đại 10",
    "thumb": "https://example.com/images/sofa.jpg",
    "desc": "Ghế sofa hiện đại với thiết kế sang trọng và thoải mái.",
    "price": 500,
    "quantity": 1500,
    "type": "furniture",
    "attributes": {
        "material": "Leather",
        "dimensions": "200x90x100 cm",
        "weight": 30
    }
}

### update product
PATCH {{url_dev}}/product/69271b152228deeb7c258501
Content-Type: application/json
x-api-key: c3c035e9650d2782af88d2139eb62e08ba4a4c8e5c083a5e2ee7e9ffae9e8515
x-client-key: 692856a91cabb8194af2176e
Authorization: Bearer {{access_token}}

{
    "name": null,
    "type": "Furniture",
    "attributes": {
      "dimensions": "200x90x100 mets"
    }
}

### publish product by id
POST {{url_dev}}/product/publish/69285746e1d62ec935fef5c8
Content-Type: application/json
x-api-key: c3c035e9650d2782af88d2139eb62e08ba4a4c8e5c083a5e2ee7e9ffae9e8515
x-client-key: 692856a91cabb8194af2176e
Authorization: Bearer {{access_token}}

### unPublish product by id
POST {{url_dev}}/product/unpublish/6926a6013ad38d006b2287ce
Content-Type: application/json
x-api-key: c3c035e9650d2782af88d2139eb62e08ba4a4c8e5c083a5e2ee7e9ffae9e8515
x-client-key: 692856a91cabb8194af2176e
Authorization: Bearer {{access_token}}

### find all draft products for shop
GET {{url_dev}}/product/drafts/all?limit=50&skip=0
Content-Type: application/json
x-api-key: c3c035e9650d2782af88d2139eb62e08ba4a4c8e5c083a5e2ee7e9ffae9e8515
x-client-key: 692856a91cabb8194af2176e
Authorization: Bearer {{access_token}}

### find all published products for shop
GET {{url_dev}}/product/published/all?limit=50&skip=0
Content-Type: application/json
x-api-key: c3c035e9650d2782af88d2139eb62e08ba4a4c8e5c083a5e2ee7e9ffae9e8515
x-client-key: 692856a91cabb8194af2176e
Authorization: Bearer {{access_token}}

### search products by user
GET {{url_dev}}/product/search/sofa
Content-Type: application/json
x-api-key: c3c035e9650d2782af88d2139eb62e08ba4a4c8e5c083a5e2ee7e9ffae9e8515
x-client-key: 692856a91cabb8194af2176e
Authorization: Bearer {{access_token}}

### find all products for user
GET {{url_dev}}/product/
Content-Type: application/json
x-api-key: c3c035e9650d2782af88d2139eb62e08ba4a4c8e5c083a5e2ee7e9ffae9e8515
x-client-key: 692856a91cabb8194af2176e
Authorization: Bearer {{access_token}}

### find product for user
GET {{url_dev}}/product/6926a6013ad38d006b2287ce
Content-Type: application/json
x-api-key: c3c035e9650d2782af88d2139eb62e08ba4a4c8e5c083a5e2ee7e9ffae9e8515
x-client-key: 692856a91cabb8194af2176e
Authorization: Bearer {{access_token}}
