@url_dev=http://localhost:9000/api/v1
@access_token=eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2OTI1YzY5OTZlMTkwM2Y1NjIxYTk5MjEiLCJpYXQiOjE3NjQxNjk4ODksImV4cCI6MTc2NDM0MjY4OX0.Oj9k8anwsBPE6js_Ia8L-_45bo3CVfmih4ZrQdIn3Mo74wysNKg6gqs_jNKb69YSyb4KjL8EiQqKAdUz-GGXUXVfh6Lk_OGlRnX_GpKzQrC876GizSpRXcqb4a7nF8uQwX1-r00YcxqlS9V8weUHPQVa2_Sa-k8qFVQhdTMAwuDdVIdwx5lOZmUDjTPg0xgpfi0x6dfNgxfagA1lr2MXi5-sO0cY6zb8deZt46BfiqpR-l6sy0FIc0-3ZEnPkHKtz_8A20T7kLpX8QrhqDjX35ovP30mTvdzhP-27Vef07IevB7SVWbXKUuEU1bLRFewfvJLqYc44xjdsXDmQlGQnT12_YDUjwNhaagIzwPxRkFCmlSdYWHkkcv9xoCbuYYp4DMrOk62S_gs7bwhSs9L0BuBu-a46VxyMTAEdPJ-y9O1M7nQCwmU-9e9dNd7EGgA7FhDVvFT60UxBHDA6AUyifiAob-hwE4TheUF5NAxYDQckiz7Ecfb4tPT6DRYxrVde-d7WiR8pGI3DKGl9XGI5j1Bq0Gfon9k9LiFc66fD4gjzGKtBO8IJT45fHBEOUR9KZjKzUKkb0L5T3aeNlcgb68-8xzrvPe_VA-xGBl7z4hgKB8HEno9gykV8wB0oS3hE99VG6ZImP9qxtsrt9IsfF4JAk33_z8GLNgNaPTeZME
@refresh_token=eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2OTI1YzY5OTZlMTkwM2Y1NjIxYTk5MjEiLCJpYXQiOjE3NjQxNjk4ODksImV4cCI6MTc2NDc3NDY4OX0.OliyRjLDbE5KyGgg5TnOXeQy_oH_yopPk2wNDtS93jpkSYjEsYtsDaLPHz52WT1vjdDk96Je0nOjZ1wKtw2PtZWQs1KY3v8d6zP2LVFgJ3p2DWJdLIlupT-P-HAoMVaH35F9IrWgRIwLbfDZU3HirslAvX6XTJjZldecpRxlAm7PFvcspXkCJutZzlM1IUSvqT4J_O7FI5dca_ND6z4xkc2TXZt3ZA9bIrmS7ORcpkYGOt84I-0CZyzIcmQ4zX4fpyE9Lqc14eeb1nq6odj4-XNMAzTXIU2tVIPOuTxxxmKfHDwHZNsRLHiYePxATRd1gNeWgBL08KzFrVMwXIFRw_4qlX45QbHLUTZ9tAgG2haggLE2yuYwrdrvF0U6Sq9zOFN1mctZvHTdHG43lmMsJjaDeHY2gvkbhttI3nKUdTAZ6e-ubtPtJKvKfBxO4xvijWtSgoGmXXD-3Kn0kzeXRFFLUiziBBOD58dXiYXaqxaM_9sm9qT_mjGGzErzGGazwWqoAxkKXQ2eT6VeOuU8Ddm4KhvDAcQjfejGdhOlQUp1I7kekvO9TCcFZyelW-BgR7aPPyF9RuFQmrRqMsCA4vFiMjAZBDPqOCPuhcY-4A5vQNx0ItTQDd8lrtbJqDt5HMxUv31uOXbJ9A_AqfqJUC7T_BIhpKLOC6naoECTL_0

### cerate product
POST {{url_dev}}/product/
Content-Type: application/json
x-api-key: d1f72141cda389d4266d8a5604aa2c9a5bef71ea53498cf706bbd81248587d28
x-client-key: 6925c6996e1903f5621a9921
Authorization: Bearer {{access_token}}

{
    "name": "Ghế quỳ hiện đại",
    "thumb": "https://example.com/images/sofa.jpg",
    "desc": "Ghế sofa hiện đại với thiết kế sang trọng và thoải mái.",
    "price": 500,
    "quantity": 1500,
    "type": "Furniture",
    "attributes": {
        "material": "Leather",
        "dimensions": "200x90x100 cm",
        "weight": 30
    }
}

### update product
PATCH {{url_dev}}/product/69271b152228deeb7c258501
Content-Type: application/json
x-api-key: d1f72141cda389d4266d8a5604aa2c9a5bef71ea53498cf706bbd81248587d28
x-client-key: 6925c6996e1903f5621a9921
Authorization: Bearer {{access_token}}

{
    "name": null,
    "type": "Furniture",
    "attributes": {
      "dimensions": "200x90x100 mets"
    }
}

### publish product by id
POST {{url_dev}}/product/publish/69267d2e7f1bcabccd8504a7
Content-Type: application/json
x-api-key: d1f72141cda389d4266d8a5604aa2c9a5bef71ea53498cf706bbd81248587d28
x-client-key: 6925c6996e1903f5621a9921
Authorization: Bearer {{access_token}}

### unPublish product by id
POST {{url_dev}}/product/unpublish/6926a6013ad38d006b2287ce
Content-Type: application/json
x-api-key: d1f72141cda389d4266d8a5604aa2c9a5bef71ea53498cf706bbd81248587d28
x-client-key: 6925c6996e1903f5621a9921
Authorization: Bearer {{access_token}}

### find all draft products for shop
GET {{url_dev}}/product/drafts/all?limit=50&skip=0
Content-Type: application/json
x-api-key: d1f72141cda389d4266d8a5604aa2c9a5bef71ea53498cf706bbd81248587d28
x-client-key: 6925c6996e1903f5621a9921
Authorization: Bearer {{access_token}}

### find all published products for shop
GET {{url_dev}}/product/published/all?limit=50&skip=0
Content-Type: application/json
x-api-key: d1f72141cda389d4266d8a5604aa2c9a5bef71ea53498cf706bbd81248587d28
x-client-key: 6925c6996e1903f5621a9921
Authorization: Bearer {{access_token}}

### search products by user
GET {{url_dev}}/product/search/sofa
Content-Type: application/json
x-api-key: d1f72141cda389d4266d8a5604aa2c9a5bef71ea53498cf706bbd81248587d28
x-client-key: 6925c6996e1903f5621a9921
Authorization: Bearer {{access_token}}

### find all products for user
GET {{url_dev}}/product/
Content-Type: application/json
x-api-key: d1f72141cda389d4266d8a5604aa2c9a5bef71ea53498cf706bbd81248587d28
x-client-key: 6925c6996e1903f5621a9921
Authorization: Bearer {{access_token}}

### find product for user
GET {{url_dev}}/product/6926a6013ad38d006b2287ce
Content-Type: application/json
x-api-key: d1f72141cda389d4266d8a5604aa2c9a5bef71ea53498cf706bbd81248587d28
x-client-key: 6925c6996e1903f5621a9921
Authorization: Bearer {{access_token}}
